language: node_js
node_js: 8
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script:
  - electron-mocha test/*.main.test.js
  - electron-mocha --renderer test/*.renderer.test.js
